// <auto-generated />
using Anatomia.Comunes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anatomia.Comunes.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Anatomia.Comunes.Data.Entidades.Insercion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodInsercion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("MusculoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreInsercion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("MusculoId");

                    b.HasIndex(new[] { "CodInsercion" }, "UQ_Insercion_CodInsercion")
                        .IsUnique();

                    b.ToTable("Inserciones");
                });

            modelBuilder.Entity("Anatomia.Comunes.Data.Entidades.Musculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodMusculo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NombreMusculo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodMusculo" }, "UQ_Musculo_CodMusculo")
                        .IsUnique();

                    b.ToTable("Musculos");
                });

            modelBuilder.Entity("Anatomia.Comunes.Data.Entidades.Insercion", b =>
                {
                    b.HasOne("Anatomia.Comunes.Data.Entidades.Musculo", "Musculo")
                        .WithMany("Inserciones")
                        .HasForeignKey("MusculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musculo");
                });

            modelBuilder.Entity("Anatomia.Comunes.Data.Entidades.Musculo", b =>
                {
                    b.Navigation("Inserciones");
                });
#pragma warning restore 612, 618
        }
    }
}
